spring.application.name=Shadowbase-1

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

# ==============================
# Kafka
# ==============================

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=shadowbase-consumer

spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer




